{% set name = "djangorestframework-stubs" %}
{% set version = "3.14.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/djangorestframework-stubs-{{ version }}.tar.gz
  sha256: 4a9169253d2d46885a007c085d64e96efc8a78bd938c747e9ad0654725c4e7d0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools <64
  run:
    - django-stubs >=4.2.2
    - mypy >=0.991
    - python >=3.8
    - requests >=2.0.0
    - typing-extensions >=3.10.0
    - types-pyyaml >=5.4.3
    - types-requests >=0.1.12


test:
  imports:
    - mypy_drf_plugin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/typeddjango/djangorestframework-stubs
  summary: PEP-484 stubs for django-rest-framework
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
