{% set name = "djangorestframework-stubs" %}
{% set version = "3.15.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f60ee1c80abb01a77acc0169969e07c45c2739ae64667b9a0dd4a2e32697dcab

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - django-stubs >=5.0.0
    - typing-extensions >=3.10.0
    - requests >=2.0.0
    - types-requests >=0.1.12
    - types-pyyaml >=5.4.3

test:
  imports:
    - mypy_drf_plugin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/typeddjango/djangorestframework-stubs
  summary: PEP-484 stubs for django-rest-framework
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
