{% set name = "djangorestframework-stubs" %}
{% set version = "1.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/djangorestframework-stubs-{{ version }}.tar.gz
  sha256: 9abf25d54a11930fe0fc97d0769e1ed58db8dfc134b1fdbd76bbbaaa932ef180

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools <64
  run:
    - django-stubs >=1.13.0
    - mypy >=0.980
    - python >=3.7
    - requests >=2.0.0
    - typing-extensions >=3.10.0
    - types-pyyaml >=5.4.3
    - types-requests >=0.1.12


test:
  imports:
    - mypy_drf_plugin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/typeddjango/djangorestframework-stubs
  summary: PEP-484 stubs for django-rest-framework
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
