{% set name = "djangorestframework-stubs" %}
{% set version = "1.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/djangorestframework-stubs-{{ version }}.tar.gz
  sha256: 6e8a80a0716d8af02aa387dae47f8ef97b6c0efdf159d83a5918d582f8b1ea07

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python-coreapi >=2.0.0
    - django-stubs >=1.11.0
    - mypy >=0.950
    - python >=3.7
    - requests >=2.0.0
    - typing-extensions >=3.10.0
    - types-markdown >=0.1.5
    - types-pyyaml >=5.4.3
    - types-requests >=0.1.12


test:
  imports:
    - mypy_drf_plugin
    - mypy_drf_plugin.lib
    - mypy_drf_plugin.transformers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/typeddjango/djangorestframework-stubs
  summary: PEP-484 stubs for django-rest-framework
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
