schema_version: 1

context:
  name: djangorestframework-stubs
  version: "3.16.6"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: b8d3e73604280f69c628ff7900f0e84703d9ff47cd050fccb5f751438e4c5813

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - uv-build >=0.8.19,<0.10.0
  run:
    - python >=${{ python_min }}
    - django-stubs >=5.2.8
    - typing_extensions >=4.0
    - requests >=2.0
    - types-requests
    - types-pyyaml

tests:
  - python:
      imports:
        - mypy_drf_plugin
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: PEP-484 stubs for django-rest-framework
  license: MIT
  license_file: LICENSE.txt
  homepage: https://github.com/typeddjango/djangorestframework-stubs

extra:
  recipe-maintainers:
    - thewchan
